### ISSUE TITLE
Problem : include_tasks

### ISSUE THREAD

**Issue by LouArun** [oasis-roles/rhsm#13]
Hello Sean,

After creating an Ansible playbook and inventory file, I've encountered some problems with repo_only.yml and subscribe.yml.

[root@deployer74 rhsm]# ansible-playbook -i inventory rhsm.yml --limit=all_nodes

PLAY [rhsm-servers] *************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
ok: [master]
ok: [worker]
ok: [lb]

TASK [rhsm : Ensure subscription-manager is installed] **************************************************************************************************************************************************************************************
ok: [worker]
ok: [master]
ok: [lb]

TASK [rhsm : include_tasks] *****************************************************************************************************************************************************************************************************************
skipping: [master]
skipping: [worker]
skipping: [lb]

TASK [rhsm : include_tasks] *****************************************************************************************************************************************************************************************************************
included: /etc/ansible/roles/rhsm/tasks/subscribe.yml for master, worker, lb

TASK [rhsm : Register system to RHSM provider] **********************************************************************************************************************************************************************************************
ok: [worker]
ok: [lb]
ok: [master]

TASK [rhsm : include_tasks] *****************************************************************************************************************************************************************************************************************
fatal: [worker]: FAILED! => {"failed": true, "reason": "no action detected in task. This often indicates a misspelled module name, or incorrect module path.\n\nThe error appears to have been in '/etc/ansible/roles/rhsm/tasks/repo_only.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Enable specific repositories\n  ^ here\n\n\nThe error appears to have been in '/etc/ansible/roles/rhsm/tasks/repo_only.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Enable specific repositories\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleParserError'>\nexception: no action detected in task. This often indicates a misspelled module name, or incorrect module path.\n\nThe error appears to have been in '/etc/ansible/roles/rhsm/tasks/repo_only.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Enable specific repositories\n  ^ here\n"}
fatal: [master]: FAILED! => {"failed": true, "reason": "no action detected in task. This often indicates a misspelled module name, or incorrect module path.\n\nThe error appears to have been in '/etc/ansible/roles/rhsm/tasks/repo_only.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Enable specific repositories\n  ^ here\n\n\nThe error appears to have been in '/etc/ansible/roles/rhsm/tasks/repo_only.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Enable specific repositories\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleParserError'>\nexception: no action detected in task. This often indicates a misspelled module name, or incorrect module path.\n\nThe error appears to have been in '/etc/ansible/roles/rhsm/tasks/repo_only.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Enable specific repositories\n  ^ here\n"}
fatal: [lb]: FAILED! => {"failed": true, "reason": "no action detected in task. This often indicates a misspelled module name, or incorrect module path.\n\nThe error appears to have been in '/etc/ansible/roles/rhsm/tasks/repo_only.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Enable specific repositories\n  ^ here\n\n\nThe error appears to have been in '/etc/ansible/roles/rhsm/tasks/repo_only.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Enable specific repositories\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleParserError'>\nexception: no action detected in task. This often indicates a misspelled module name, or incorrect module path.\n\nThe error appears to have been in '/etc/ansible/roles/rhsm/tasks/repo_only.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Enable specific repositories\n  ^ here\n"}
        to retry, use: --limit @/root/test/rhsm/tasks/rhsm.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
lb : ok=4    changed=0    unreachable=0    failed=1
master : ok=4    changed=0    unreachable=0    failed=1
worker : ok=4    changed=0    unreachable=0    failed=1

Do you have an idea of where I have mistaken ? The version of Ansible is 2.4.6.

Thanks,

Arun Louvois

**Comment by greg-hellings** [comment]
It looks like this module needs to claim Ansible 2.5+ instead of 2.4+ as its minimum compatible version. It uses an Ansible module that was first introduced in 2.5. There are ways this could be worked around to bring the required version of Ansible down to 2.4.

Are you able to move to Ansible 2.5 or later, or is it important that we enable older versions of Ansible to work with this role?

**Comment by LouArun** [comment]
Thanks a lot for your answer. Yes I'm able to move to ansible 2.5. I'll give you the results when I have done the update.

**Comment by LouArun** [comment]
Perfect Sean. As you said Ansible needs to be at least 2.5. Thanks.

**Comment by tehsmyers** [comment]
I'm putting together a patch now that will (hopefully!) fix the role to work on ansible 2.4, so hopefully this won't bite you or anyone else in the future. My apologies for the oversight, and thanks for stopping by!
